### ISSUE TITLE
the method dispatch is not defined for class ChangeThemeBloc

### ISSUE THREAD

**Issue by ABINASH56** [bimsina/wallpaper#4]

**Comment by KinmoCode** [comment]
请问你解决了吗，这个问题？

Have you solved this problem?

**Comment by ABINASH56** [comment]
No .I opened this issue even on stackoverflow but no one knows what is the issue..I tried changing Bloc version but it still not working please help

**Comment by ABINASH56** [comment]
> 请问你解决了吗，这个问题？
> 
> Have you solved this problem?

No .I opened this issue even on stackoverflow but no one knows what is the issue..I tried changing Bloc version but it still not working please help

**Comment by phanirithvij** [comment]
It's an API change in the bloc library
https://dev.to/mhadaily/upgrade-to-bloc-library-v1-0-0-for-flutter-and-angular-dart-2np0

It is occurring because we did a flutter pub upgrade.
```shell
flutter pub upgrade
```

To be able to build follow these steps.

- Change all the `dispatch` calls to `add`
- Migrate to Android X (only if the build fails)

the `dispatch` method was removed recently and was changed to `add`.
